'use client';

import React from 'react';
import { View, Text, Image, StyleSheet } from '@react-pdf/renderer';

// Adjust these paths as needed if the app's structure changes
const logoIITBHU = '/Images/export/logo_iitbhu.png';
const logoRight = '/Images/export/right1_slcr.png';

const styles = StyleSheet.create({
  container: {
    flexDirection: 'column',
    width: '100%',
    marginBottom: 40,
  },
  logosRow: {
    flexDirection: 'row',
    width: '100%',
    justifyContent: 'space-between',
    marginBottom: 10,
  },
  logo: {
    width: 70,
    height: 70,
    objectFit: 'contain',
  },
  heading: {
    fontSize: 22,
    fontWeight: 'bold',
    textAlign: 'center',
    marginBottom: 50,
    marginTop: 12,
  },
  midText: {
    fontSize: 15,
    textAlign: 'center',
    marginTop: 70, // This moves it further in the middle, adjust as needed
  }
});

const HeaderSection = () => (
  <View fixed break={false} style={styles.container}>
    {/* Logos Row */}
    <View style={styles.logosRow}>
      <Image src={logoIITBHU} style={styles.logo} />
      <Image src={logoRight} style={styles.logo} />
    </View>
    {/* Page Heading */}
    <Text style={styles.heading}>Surface Water Assessment Report</Text>
    {/* Centered Middle Text */}
    <Text style={styles.midText}>Report generated by DSS-IIT BHU WRM</Text>
  </View>
);

export default HeaderSection;
