
services:
  backend:
    build:
      context: ./backend/
      dockerfile: docker/dockerfile.backend
    image: backend:latest
    ports:
      - "9000:8000"
    env_file:
      - .env
    volumes:
      - ./backend:/home/app
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload 
    restart: always
    
  db:
    image: postgres:15-alpine
    ports:
      - "5430:5432"
    restart: always
    expose:
      - "5430"
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:

