# Generated by Django 5.1.6 on 2025-10-06 12:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("gwa", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Well",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("DISTRICT", models.CharField(blank=True, max_length=100, null=True)),
                ("Location", models.CharField(blank=True, max_length=100, null=True)),
                ("Longitude", models.FloatField(blank=True, null=True)),
                ("Latitude", models.FloatField(blank=True, null=True)),
                (
                    "ph_level",
                    models.FloatField(
                        blank=True, help_text="pH level of water", null=True
                    ),
                ),
                (
                    "electrical_conductivity",
                    models.FloatField(
                        blank=True, help_text="Electrical conductivity", null=True
                    ),
                ),
                (
                    "carbonate",
                    models.FloatField(
                        blank=True, help_text="Carbonate content", null=True
                    ),
                ),
                (
                    "bicarbonate",
                    models.FloatField(
                        blank=True, help_text="Bicarbonate content", null=True
                    ),
                ),
                (
                    "chloride",
                    models.FloatField(
                        blank=True, help_text="Chloride content", null=True
                    ),
                ),
                (
                    "fluoride",
                    models.FloatField(
                        blank=True, help_text="Fluoride content", null=True
                    ),
                ),
                (
                    "sulfate",
                    models.FloatField(
                        blank=True, help_text="Sulfate content", null=True
                    ),
                ),
                (
                    "nitrate",
                    models.FloatField(
                        blank=True, help_text="Nitrate content", null=True
                    ),
                ),
                (
                    "phosphate",
                    models.FloatField(
                        blank=True, help_text="Phosphate content", null=True
                    ),
                ),
                (
                    "Hardness",
                    models.FloatField(
                        blank=True, help_text="Water hardness", null=True
                    ),
                ),
                (
                    "calcium",
                    models.FloatField(
                        blank=True, help_text="Calcium content", null=True
                    ),
                ),
                (
                    "magnesium",
                    models.FloatField(
                        blank=True, help_text="Magnesium content", null=True
                    ),
                ),
                (
                    "sodium",
                    models.FloatField(
                        blank=True, help_text="Sodium content", null=True
                    ),
                ),
                (
                    "potassium",
                    models.FloatField(
                        blank=True, help_text="Potassium content", null=True
                    ),
                ),
                (
                    "iron",
                    models.FloatField(blank=True, help_text="Iron content", null=True),
                ),
                (
                    "arsenic",
                    models.FloatField(
                        blank=True, help_text="Arsenic content", null=True
                    ),
                ),
                (
                    "uranium",
                    models.FloatField(
                        blank=True, help_text="Uranium content", null=True
                    ),
                ),
                ("FID_Village", models.IntegerField(blank=True, null=True)),
                ("village", models.CharField(blank=True, max_length=100, null=True)),
                ("SUB_DISTRI", models.CharField(blank=True, max_length=100, null=True)),
                ("SUBDIS_COD", models.IntegerField(blank=True, null=True)),
                ("DISTRICT_1", models.CharField(blank=True, max_length=100, null=True)),
                ("DISTRICT_C", models.IntegerField(blank=True, null=True)),
                ("STATE", models.CharField(blank=True, max_length=100, null=True)),
                ("STATE_CODE", models.IntegerField(blank=True, null=True)),
                (
                    "YEAR",
                    models.IntegerField(
                        blank=True, help_text="Sample collection year", null=True
                    ),
                ),
                (
                    "village_code",
                    models.ForeignKey(
                        db_column="village_code",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="gwa_wells",
                        to="gwa.village",
                    ),
                ),
            ],
        ),
    ]
