# Generated by Django 5.1.6 on 2025-12-09 09:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("management", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="personalemployee",
            old_name="supervisor",
            new_name="supervisor_name",
        ),
        migrations.AddField(
            model_name="personalemployee",
            name="supervisor_email",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="employees",
                to="management.personaladmin",
                to_field="email",
            ),
        ),
    ]
