# Generated by Django 5.1.6 on 2025-12-08 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("management", "0002_personalemployee"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="personalemployee",
            options={
                "verbose_name": "Personal Employee",
                "verbose_name_plural": "Personal Employees",
            },
        ),
        migrations.AddField(
            model_name="personalemployee",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterModelTable(
            name="personalemployee",
            table="personal_employee",
        ),
    ]
