# Generated by Django 5.1.6 on 2025-05-27 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authapp", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="logincredential",
            name="password",
            field=models.CharField(max_length=128),
        ),
        migrations.AlterModelTable(
            name="logincredential",
            table="login_credentials",
        ),
    ]
