# Generated by Django 5.1.6 on 2025-05-30 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authapp", "0002_alter_logincredential_password_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="logincredential",
            name="email",
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
    ]
