# Generated by Django 5.1.6 on 2025-04-28 05:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Basic", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="PopulationCohort",
        ),
    ]
