# Generated by Django 5.1.6 on 2025-04-29 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Basic", "0002_delete_populationcohort"),
    ]

    operations = [
        migrations.CreateModel(
            name="Population2011Cohort",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("state_code", models.IntegerField()),
                ("district_code", models.IntegerField()),
                ("subdistrict_code", models.IntegerField()),
                ("village_code", models.IntegerField()),
                ("region_name", models.CharField(max_length=100)),
                ("population_0_14_male", models.BigIntegerField()),
                ("population_0_14_female", models.BigIntegerField()),
                ("population_15_54_male", models.BigIntegerField()),
                ("population_15_54_female", models.BigIntegerField()),
                ("population_55_plus_male", models.BigIntegerField()),
                ("population_55_plus_female", models.BigIntegerField()),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=(
                            "state_code",
                            "district_code",
                            "subdistrict_code",
                            "village_code",
                            "region_name",
                        ),
                        name="unique_region_2011",
                    )
                ],
            },
        ),
    ]
