# Generated by Django 5.1.6 on 2025-04-29 06:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Basic", "0003_population2011cohort"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Population2011Cohort",
        ),
    ]
