# Generated by Django 5.1.6 on 2025-04-29 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Basic", "0004_delete_population2011cohort"),
    ]

    operations = [
        migrations.CreateModel(
            name="PopulationCohort",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("state_code", models.BigIntegerField()),
                ("district_code", models.BigIntegerField()),
                ("subdistrict_code", models.BigIntegerField()),
                ("village_code", models.BigIntegerField()),
                ("region_name", models.CharField(max_length=100)),
                ("year", models.IntegerField()),
                ("age_group", models.CharField(max_length=20)),
                ("gender", models.CharField(max_length=10)),
                ("population", models.BigIntegerField()),
            ],
        ),
    ]
