# Generated by Django 5.1.6 on 2025-08-11 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Basic", "0005_populationcohort"),
    ]

    operations = [
        migrations.CreateModel(
            name="RunoffCoefficient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("duration_minutes", models.IntegerField()),
                ("sector_impervious", models.FloatField()),
                ("sector_60_impervious", models.FloatField()),
                ("sector_40_impervious", models.FloatField()),
                ("sector_pervious", models.FloatField()),
                ("rectangle_impervious", models.FloatField()),
                ("rectangle_50_impervious", models.FloatField()),
                ("rectangle_30_impervious", models.FloatField()),
                ("rectangle_pervious", models.FloatField()),
            ],
            options={
                "verbose_name": "Runoff Coefficient",
                "verbose_name_plural": "Runoff Coefficients",
                "ordering": ["duration_minutes"],
            },
        ),
    ]
