# Generated by Django 5.1.6 on 2025-08-11 04:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Basic", "0006_runoffcoefficient"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="RunoffCoefficient",
            new_name="BasicRunoffCoefficient",
        ),
        migrations.AlterModelOptions(
            name="basicrunoffcoefficient",
            options={"ordering": ["duration_t_minutes"]},
        ),
        migrations.RenameField(
            model_name="basicrunoffcoefficient",
            old_name="duration_minutes",
            new_name="duration_t_minutes",
        ),
        migrations.RenameField(
            model_name="basicrunoffcoefficient",
            old_name="rectangle_30_impervious",
            new_name="rectangle_30percent_impervious",
        ),
        migrations.RenameField(
            model_name="basicrunoffcoefficient",
            old_name="rectangle_50_impervious",
            new_name="rectangle_50percent_impervious",
        ),
        migrations.RenameField(
            model_name="basicrunoffcoefficient",
            old_name="sector_40_impervious",
            new_name="sector_40percent_impervious",
        ),
        migrations.RenameField(
            model_name="basicrunoffcoefficient",
            old_name="sector_60_impervious",
            new_name="sector_60percent_impervious",
        ),
        migrations.AlterModelTable(
            name="basicrunoffcoefficient",
            table="basic_runoffcoefficient",
        ),
    ]
