# Generated by Django 5.1.6 on 2025-09-08 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DrainWaterQuality",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("location", models.CharField(max_length=150)),
                ("ph", models.FloatField()),
                ("temp", models.FloatField()),
                ("ec_us_cm", models.FloatField(verbose_name="EC (μS/cm)")),
                ("tds_ppm", models.FloatField(verbose_name="TDS (ppm)")),
                ("do_mg_l", models.FloatField(verbose_name="DO (mg/L)")),
                ("turbidity", models.FloatField()),
                ("tss_mg_l", models.FloatField(verbose_name="TSS (mg/L)")),
                ("cod", models.FloatField()),
                ("bod_mg_l", models.FloatField(verbose_name="BOD (mg/L)")),
                ("ts_mg_l", models.FloatField(verbose_name="TS (mg/L)")),
                ("chloride", models.FloatField()),
                ("nitrate", models.FloatField(blank=True, null=True)),
                ("faecal_col", models.CharField(blank=True, max_length=100, null=True)),
                ("total_col", models.CharField(blank=True, max_length=100, null=True)),
                ("lat", models.FloatField(blank=True, null=True)),
                ("lon", models.FloatField(blank=True, null=True)),
                ("stream", models.CharField(blank=True, max_length=255, null=True)),
                ("observation", models.TextField(blank=True, null=True)),
                ("remarks", models.TextField(blank=True, null=True)),
            ],
        ),
    ]
