# Generated by Django 5.1.6 on 2025-09-03 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SubbasinFlow",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sub", models.IntegerField()),
                ("year", models.IntegerField()),
                ("month", models.IntegerField()),
                ("area_km2", models.FloatField()),
                ("flow_in_cms", models.FloatField()),
                ("flow_out_cms", models.FloatField()),
                ("yyyyddd", models.IntegerField()),
            ],
            options={
                "db_table": "subbasin_flow",
                "indexes": [
                    models.Index(fields=["sub"], name="subbasin_fl_sub_06d5d1_idx"),
                    models.Index(
                        fields=["year", "month"], name="subbasin_fl_year_68693c_idx"
                    ),
                ],
            },
        ),
    ]
