# Generated by Django 5.1.6 on 2025-09-19 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("swa", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ClimateDrain",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sub", models.IntegerField()),
                ("year", models.IntegerField()),
                ("mon", models.IntegerField()),
                ("areakm2", models.FloatField()),
                ("flow_incms", models.FloatField()),
                ("flow_outcms", models.FloatField()),
                ("yyyymm", models.IntegerField()),
                ("rch", models.IntegerField()),
            ],
            options={
                "db_table": "climate_drain",
                "indexes": [
                    models.Index(fields=["sub"], name="climate_dra_sub_1d6158_idx"),
                    models.Index(
                        fields=["year", "mon"], name="climate_dra_year_2c4b3d_idx"
                    ),
                    models.Index(
                        fields=["yyyymm"], name="climate_dra_yyyymm_f70357_idx"
                    ),
                    models.Index(fields=["rch"], name="climate_dra_rch_451c1d_idx"),
                ],
            },
        ),
    ]
