# Generated by Django 5.1.6 on 2025-09-26 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("swa", "0002_climatedrain"),
    ]

    operations = [
        migrations.CreateModel(
            name="AdminFlow",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("vlcode", models.BigIntegerField()),
                ("village", models.CharField(max_length=255)),
                ("year", models.IntegerField()),
                ("mon", models.IntegerField()),
                ("surq_cnt_m3", models.FloatField()),
                ("subdistrict_code_id", models.IntegerField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Admin Flow",
                "verbose_name_plural": "Admin Flows",
                "db_table": "adminflow",
            },
        ),
        migrations.CreateModel(
            name="ClimateAdmin",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("vlcode", models.BigIntegerField()),
                ("village", models.CharField(max_length=255)),
                ("year", models.IntegerField(db_column="YEAR")),
                ("mon", models.IntegerField(db_column="MON")),
                ("surq_cnt_m3", models.FloatField(db_column="SURQ_CNT_m3")),
                ("source_id", models.IntegerField()),
                ("subdistrict_code_id", models.IntegerField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Climate Admin",
                "verbose_name_plural": "Climate Admins",
                "db_table": "climate_admin",
            },
        ),
    ]
