# Generated by Django 5.1.6 on 2025-10-16 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ShapefileRecord",
            fields=[
                ("fid", models.AutoField(primary_key=True, serialize=False)),
                ("shapefile_name", models.CharField(max_length=255)),
                ("shapefile_path", models.CharField(max_length=500)),
            ],
            options={
                "verbose_name": "Shapefile Record",
                "verbose_name_plural": "Shapefile Records",
                "db_table": "shapefile_record",
            },
        ),
    ]
