# Generated by Django 5.1.6 on 2025-12-02 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="GroundWaterData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("blockcode", models.IntegerField()),
                ("SUBDIS_COD", models.IntegerField()),
                ("vlcode", models.IntegerField(unique=True)),
                ("village", models.CharField(max_length=255)),
                ("blockname", models.CharField(max_length=255)),
                ("Total_Geographical_Area", models.FloatField(blank=True, null=True)),
                ("Recharge_Worthy_Area", models.FloatField(blank=True, null=True)),
                (
                    "Recharge_from_Rainfall_MON",
                    models.FloatField(blank=True, null=True),
                ),
                (
                    "Recharge_from_Other_Sources_MON",
                    models.FloatField(blank=True, null=True),
                ),
                ("Recharge_from_Rainfall_NM", models.FloatField(blank=True, null=True)),
                (
                    "Recharge_from_Other_Sources_NM",
                    models.FloatField(blank=True, null=True),
                ),
                (
                    "Total_Annual_Ground_Water_Recharge",
                    models.FloatField(blank=True, null=True),
                ),
                ("Total_Natural_Discharges", models.FloatField(blank=True, null=True)),
                (
                    "Annual_Extractable_Ground_Water_Resource",
                    models.FloatField(blank=True, null=True),
                ),
                ("Irrigation_Use", models.FloatField(blank=True, null=True)),
                ("Domestic_Use", models.FloatField(blank=True, null=True)),
                ("Total_Extraction", models.FloatField(blank=True, null=True)),
                (
                    "Net_Ground_Water_Availability_for_future_use",
                    models.FloatField(blank=True, null=True),
                ),
                (
                    "Stage_of_Ground_Water_Extraction",
                    models.FloatField(blank=True, null=True),
                ),
                (
                    "Annual_GW_Allocation_for_Domestic_Use_as_on_2025",
                    models.FloatField(blank=True, null=True),
                ),
                ("Industrial_Use", models.FloatField(blank=True, null=True)),
                ("Year", models.CharField(max_length=50)),
            ],
        ),
    ]
