# Generated by Django 5.1.6 on 2025-12-01 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rsq", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="groundwaterdata",
            name="Annual_Extractable_Ground_Water_Resource",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="groundwaterdata",
            name="Annual_GW_Allocation_for_Domestic_Use_as_on_2025",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="groundwaterdata",
            name="Domestic_Use",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="groundwaterdata",
            name="Industrial_Use",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="groundwaterdata",
            name="Irrigation_Use",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="groundwaterdata",
            name="Net_Ground_Water_Availability_for_future_use",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="groundwaterdata",
            name="Recharge_Worthy_Area",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="groundwaterdata",
            name="Recharge_from_Other_Sources_MON",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="groundwaterdata",
            name="Recharge_from_Other_Sources_NM",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="groundwaterdata",
            name="Recharge_from_Rainfall_MON",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="groundwaterdata",
            name="Recharge_from_Rainfall_NM",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="groundwaterdata",
            name="Stage_of_Ground_Water_Extraction",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="groundwaterdata",
            name="Total_Annual_Ground_Water_Recharge",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="groundwaterdata",
            name="Total_Extraction",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="groundwaterdata",
            name="Total_Geographical_Area",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="groundwaterdata",
            name="Total_Natural_Discharges",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
