# Generated by Django 5.1.6 on 2025-12-03 06:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("rsq", "0002_block_village"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Village",
        ),
    ]
