# Generated by Django 5.1.6 on 2025-12-03 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rsq", "0003_delete_village"),
    ]

    operations = [
        migrations.CreateModel(
            name="Village",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("blockcode", models.IntegerField()),
                ("vlcode", models.IntegerField(unique=True)),
                ("village", models.CharField(max_length=255)),
            ],
            options={
                "db_table": "rsq_village",
            },
        ),
    ]
