"""add population_2011 table

Revision ID: 1cfcf8f503c7
Revises: f4448f27d4c9
Create Date: 2025-11-12 12:22:11.343464

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1cfcf8f503c7'
down_revision: Union[str, Sequence[str], None] = 'f4448f27d4c9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('gwa_village', 'subdistrict_code',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint(op.f('gwa_village_subdistrict_code_fkey'), 'gwa_village', type_='foreignkey')
    op.create_foreign_key(None, 'gwa_village', 'gwa_subdistrict', ['subdistrict_code'], ['subdistrict_code'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'gwa_village', type_='foreignkey')
    op.create_foreign_key(op.f('gwa_village_subdistrict_code_fkey'), 'gwa_village', 'population_2011', ['subdistrict_code'], ['subdistrict_code'], ondelete='CASCADE')
    op.alter_column('gwa_village', 'subdistrict_code',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
