"""create well table

Revision ID: 2b99d7f0885b
Revises: 
Create Date: 2025-11-11 18:48:36.883170

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2b99d7f0885b'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('crop',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('season', sa.String(length=100), nullable=False),
    sa.Column('crop', sa.String(length=100), nullable=False),
    sa.Column('stage', sa.String(length=100), nullable=False),
    sa.Column('period', sa.String(length=100), nullable=False),
    sa.Column('crop_factor', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_crop_id'), 'crop', ['id'], unique=False)
    op.create_table('state',
    sa.Column('state_code', sa.Integer(), nullable=False),
    sa.Column('state_name', sa.String(length=40), nullable=False),
    sa.PrimaryKeyConstraint('state_code')
    )
    op.create_table('district',
    sa.Column('district_code', sa.Integer(), nullable=False),
    sa.Column('district_name', sa.String(length=40), nullable=False),
    sa.Column('state_code', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['state_code'], ['state.state_code'], ),
    sa.PrimaryKeyConstraint('district_code')
    )
    op.create_table('subdistrict',
    sa.Column('subdistrict_code', sa.Integer(), nullable=False),
    sa.Column('subdistrict_name', sa.String(length=40), nullable=False),
    sa.Column('district_code', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['district_code'], ['district.district_code'], ),
    sa.PrimaryKeyConstraint('subdistrict_code')
    )
    op.create_table('village',
    sa.Column('village_code', sa.Integer(), nullable=False),
    sa.Column('village_name', sa.String(length=100), nullable=False),
    sa.Column('population_2011', sa.Integer(), nullable=False),
    sa.Column('subdistrict_code', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['subdistrict_code'], ['subdistrict.subdistrict_code'], ),
    sa.PrimaryKeyConstraint('village_code')
    )
    op.create_table('well',
    sa.Column('FID_clip', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('OBJECTID', sa.Integer(), nullable=False),
    sa.Column('village_code', sa.Integer(), nullable=False),
    sa.Column('shapeName', sa.String(length=100), nullable=True),
    sa.Column('SUB_DISTRI', sa.String(length=100), nullable=True),
    sa.Column('DISTRICT_C', sa.Integer(), nullable=True),
    sa.Column('DISTRICT', sa.String(length=100), nullable=True),
    sa.Column('STATE_CODE', sa.Integer(), nullable=True),
    sa.Column('STATE', sa.String(length=100), nullable=True),
    sa.Column('population', sa.Integer(), nullable=True),
    sa.Column('SUBDIS_COD', sa.Integer(), nullable=True),
    sa.Column('Area', sa.Float(), nullable=True),
    sa.Column('DISTRICT_1', sa.String(length=100), nullable=True),
    sa.Column('BLOCK', sa.String(length=100), nullable=True),
    sa.Column('HYDROGRAPH', sa.String(length=100), nullable=True),
    sa.Column('LONGITUDE', sa.Float(), nullable=True),
    sa.Column('LATITUDE', sa.Float(), nullable=True),
    sa.Column('RL', sa.Float(), nullable=True),
    sa.Column('PRE_2011', sa.Float(), nullable=True),
    sa.Column('POST_2011', sa.Float(), nullable=True),
    sa.Column('PRE_2012', sa.Float(), nullable=True),
    sa.Column('POST_2012', sa.Float(), nullable=True),
    sa.Column('PRE_2013', sa.Float(), nullable=True),
    sa.Column('POST_2013', sa.Float(), nullable=True),
    sa.Column('PRE_2014', sa.Float(), nullable=True),
    sa.Column('POST_2014', sa.Float(), nullable=True),
    sa.Column('PRE_2015', sa.Float(), nullable=True),
    sa.Column('POST_2015', sa.Float(), nullable=True),
    sa.Column('PRE_2016', sa.Float(), nullable=True),
    sa.Column('POST_2016', sa.Float(), nullable=True),
    sa.Column('PRE_2017', sa.Float(), nullable=True),
    sa.Column('POST_2017', sa.Float(), nullable=True),
    sa.Column('PRE_2018', sa.Float(), nullable=True),
    sa.Column('POST_2018', sa.Float(), nullable=True),
    sa.Column('PRE_2019', sa.Float(), nullable=True),
    sa.Column('POST_2019', sa.Float(), nullable=True),
    sa.Column('PRE_2020', sa.Float(), nullable=True),
    sa.Column('POST_2020', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['village_code'], ['village.village_code'], ),
    sa.PrimaryKeyConstraint('FID_clip')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('well')
    op.drop_table('village')
    op.drop_table('subdistrict')
    op.drop_table('district')
    op.drop_table('state')
    op.drop_index(op.f('ix_crop_id'), table_name='crop')
    op.drop_table('crop')
    # ### end Alembic commands ###
