"""initial schema

Revision ID: 9317fca93fc6
Revises: 
Create Date: 2025-11-12 06:25:46.850687

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9317fca93fc6'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gwa_state',
    sa.Column('state_code', sa.Integer(), nullable=False),
    sa.Column('state_name', sa.String(length=40), nullable=False),
    sa.PrimaryKeyConstraint('state_code')
    )
    op.create_index(op.f('ix_gwa_state_state_code'), 'gwa_state', ['state_code'], unique=False)
    op.create_table('gwa_district',
    sa.Column('district_code', sa.Integer(), nullable=False),
    sa.Column('district_name', sa.String(length=40), nullable=False),
    sa.Column('state_code', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['state_code'], ['gwa_state.state_code'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('district_code')
    )
    op.create_index(op.f('ix_gwa_district_district_code'), 'gwa_district', ['district_code'], unique=False)
    op.create_table('gwa_subdistrict',
    sa.Column('subdistrict_code', sa.Integer(), nullable=False),
    sa.Column('subdistrict_name', sa.String(length=40), nullable=False),
    sa.Column('district_code', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['district_code'], ['gwa_district.district_code'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('subdistrict_code')
    )
    op.create_index(op.f('ix_gwa_subdistrict_subdistrict_code'), 'gwa_subdistrict', ['subdistrict_code'], unique=False)
    op.create_table('gwa_village',
    sa.Column('village_code', sa.Integer(), nullable=False),
    sa.Column('village_name', sa.String(length=100), nullable=False),
    sa.Column('population_2011', sa.Integer(), nullable=False),
    sa.Column('subdistrict_code', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['subdistrict_code'], ['gwa_subdistrict.subdistrict_code'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('village_code')
    )
    op.create_index(op.f('ix_gwa_village_village_code'), 'gwa_village', ['village_code'], unique=False)
    op.create_table('gwa_well',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('village_code', sa.Integer(), nullable=False),
    sa.Column('FID_clip', sa.Integer(), nullable=True),
    sa.Column('OBJECTID', sa.Integer(), nullable=True),
    sa.Column('shapeName', sa.String(length=100), nullable=True),
    sa.Column('SUB_DISTRI', sa.String(length=100), nullable=True),
    sa.Column('DISTRICT_C', sa.Integer(), nullable=True),
    sa.Column('DISTRICT', sa.String(length=100), nullable=True),
    sa.Column('STATE_CODE', sa.Integer(), nullable=True),
    sa.Column('STATE', sa.String(length=100), nullable=True),
    sa.Column('population', sa.Integer(), nullable=True),
    sa.Column('SUBDIS_COD', sa.Integer(), nullable=True),
    sa.Column('Area', sa.Float(), nullable=True),
    sa.Column('DISTRICT_1', sa.String(length=100), nullable=True),
    sa.Column('BLOCK', sa.String(length=100), nullable=True),
    sa.Column('HYDROGRAPH', sa.String(length=100), nullable=True),
    sa.Column('LONGITUDE', sa.Float(), nullable=True),
    sa.Column('LATITUDE', sa.Float(), nullable=True),
    sa.Column('RL', sa.Float(), nullable=True),
    sa.Column('PRE_2011', sa.Float(), nullable=True),
    sa.Column('POST_2011', sa.Float(), nullable=True),
    sa.Column('PRE_2012', sa.Float(), nullable=True),
    sa.Column('POST_2012', sa.Float(), nullable=True),
    sa.Column('PRE_2013', sa.Float(), nullable=True),
    sa.Column('POST_2013', sa.Float(), nullable=True),
    sa.Column('PRE_2014', sa.Float(), nullable=True),
    sa.Column('POST_2014', sa.Float(), nullable=True),
    sa.Column('PRE_2015', sa.Float(), nullable=True),
    sa.Column('POST_2015', sa.Float(), nullable=True),
    sa.Column('PRE_2016', sa.Float(), nullable=True),
    sa.Column('POST_2016', sa.Float(), nullable=True),
    sa.Column('PRE_2017', sa.Float(), nullable=True),
    sa.Column('POST_2017', sa.Float(), nullable=True),
    sa.Column('PRE_2018', sa.Float(), nullable=True),
    sa.Column('POST_2018', sa.Float(), nullable=True),
    sa.Column('PRE_2019', sa.Float(), nullable=True),
    sa.Column('POST_2019', sa.Float(), nullable=True),
    sa.Column('PRE_2020', sa.Float(), nullable=True),
    sa.Column('POST_2020', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['village_code'], ['gwa_village.village_code'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('FID_clip')
    )
    op.create_index(op.f('ix_gwa_well_id'), 'gwa_well', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_gwa_well_id'), table_name='gwa_well')
    op.drop_table('gwa_well')
    op.drop_index(op.f('ix_gwa_village_village_code'), table_name='gwa_village')
    op.drop_table('gwa_village')
    op.drop_index(op.f('ix_gwa_subdistrict_subdistrict_code'), table_name='gwa_subdistrict')
    op.drop_table('gwa_subdistrict')
    op.drop_index(op.f('ix_gwa_district_district_code'), table_name='gwa_district')
    op.drop_table('gwa_district')
    op.drop_index(op.f('ix_gwa_state_state_code'), table_name='gwa_state')
    op.drop_table('gwa_state')
    # ### end Alembic commands ###
