"""stp

Revision ID: b2693290cc8a
Revises: 
Create Date: 2025-05-04 12:39:03.122072

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b2693290cc8a'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stp_raster',
    sa.Column('file_name', sa.String(), nullable=False),
    sa.Column('layer_name', sa.String(), nullable=False),
    sa.Column('weight', sa.Float(), nullable=False),
    sa.Column('file_path', sa.String(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('modified_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stp_raster_id'), 'stp_raster', ['id'], unique=True)
    op.create_table('stp_state',
    sa.Column('state_code', sa.Integer(), nullable=False),
    sa.Column('state_name', sa.String(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('modified_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('state_code', 'id'),
    sa.UniqueConstraint('state_code')
    )
    op.create_index(op.f('ix_stp_state_id'), 'stp_state', ['id'], unique=True)
    op.create_table('stp_district',
    sa.Column('district_code', sa.Integer(), nullable=False),
    sa.Column('district_name', sa.String(), nullable=False),
    sa.Column('state_code', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('modified_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['state_code'], ['stp_state.state_code'], ),
    sa.PrimaryKeyConstraint('district_code', 'id'),
    sa.UniqueConstraint('district_code')
    )
    op.create_index(op.f('ix_stp_district_id'), 'stp_district', ['id'], unique=True)
    op.create_table('stp_subdistrict',
    sa.Column('subdistrict_code', sa.Integer(), nullable=False),
    sa.Column('subdistrict_name', sa.String(), nullable=False),
    sa.Column('district_code', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('modified_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['district_code'], ['stp_district.district_code'], ),
    sa.PrimaryKeyConstraint('subdistrict_code', 'id'),
    sa.UniqueConstraint('subdistrict_code')
    )
    op.create_index(op.f('ix_stp_subdistrict_id'), 'stp_subdistrict', ['id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_stp_subdistrict_id'), table_name='stp_subdistrict')
    op.drop_table('stp_subdistrict')
    op.drop_index(op.f('ix_stp_district_id'), table_name='stp_district')
    op.drop_table('stp_district')
    op.drop_index(op.f('ix_stp_state_id'), table_name='stp_state')
    op.drop_table('stp_state')
    op.drop_index(op.f('ix_stp_raster_id'), table_name='stp_raster')
    op.drop_table('stp_raster')
    # ### end Alembic commands ###
